### ISSUE TITLE
Turn on speaker

### ISSUE THREAD

**Issue by mctoannguyen** [d0pam1n/DoorPhone#10]
Hi @d0pam1n,
Can you help me turn on speaker.
Thanks!

**Comment by d0pam1n** [comment]
Look at the function `setMicMuted` within the MainActivity. Especially this part.

` mAudioManager.setMicrophoneMute(state);`

**Comment by mctoannguyen** [comment]
I want use function in pjsua2 but not work, then I use mAudioManager.setSpeakerphoneOn(on);
It work.
Thanks!
