### ISSUE TITLE
Always return callStateCode = PJSIP_INV_STATE_DISCONNECTED when OutGoing

### ISSUE THREAD

**Issue by mctoannguyen** [d0pam1n/DoorPhone#9]
When make call, DoorPhone always return callStateCode = PJSIP_INV_STATE_DISCONNECTED. When I make call to auto answer then hangup right away.
p/s: Thank you, d0pam1n! Your project helped me a lot. Sorry my English is poor :D

**Comment by d0pam1n** [comment]
Hi @mctoannguyen,
you have to explain that more detailed.  I´ve tested an outgoing call in combination with doorpi without any problems. So making calls is basically working. 
Maybe it depends on your setup?

**Comment by mctoannguyen** [comment]
Hi @d0pam1n,
I had edited my config account and it worked.
Can you help me open the speaker?
Thanks!

**Comment by d0pam1n** [comment]
Please open a new issue.
